version: '2.1'

services:
    nodejs:
        image: nodejs
        build: .
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
            - 9229:9229
        command: node --inspect=0.0.0.0:9229 index.js
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: "mongodb"
        ports:
            - 27017:27017